Removing outdated video link and potentially risky images
Tuxemon/Tuxemon-Website pull request #17
Opened 2021-09-01 12:39 UTC by Sanglorian

Just thought I should be bold and get rid of a couple of broken links as well as photos that show another game in the background.

2021-09-01 13:32 UTC, xirsoi approved these changes

2021-09-08 00:53 UTC, bitcraft commented
files still in use and will need the pages edited to remove references
https://github.com/Tuxemon/Tuxemon-Website/search?q=banner-03
https://github.com/Tuxemon/Tuxemon-Website/search?q=featurette-02
https://github.com/Tuxemon/Tuxemon-Website/search?q=featurette-03

2021-09-08 00:54 UTC, bitcraft requested changes
please see comment

2021-09-10 00:51 UTC, Sanglorian commented
Thanks for reviewing, @bitcraft -- have fixed the index.ejs file. 

The other references should be fine as I ended up replacing the images instead of deleting them -- sorry for the confusing commit summaries, changed my approach halfway.

2021-09-24 02:50 UTC, merged